import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
    docsSidebar: [
        "index",
        {
            type: "category",
            label: "Code Reference",
            link: {
                type: "doc",
                id: "CutTheRopeDX/index",
            },
            items: [
                {
                    type: "autogenerated",
                    dirName: "CutTheRopeDX",
                },
            ],
        },
    ],
};

export default sidebars;
